apiVersion: v1
# give access to certain type of object types, each API version defines a different set of 'objects' we can use
kind: Pod
# kind is use to represent the type of object that we want to create, type : Pod or Service
#Objects serve different purposes - objects can be used to run a container, monitoring a container, setting up networking, etc
metadata: 
  name: client-pod
  labels:
    component: web
spec:
  containers:
    - name: client
      image: ljinan/multi-client
      ports:
        - containerPort: 3000