apiVersion: v1
kind: Pod
# kind is use to represent the type of object that we want to create, type : Pod or Service
metadata: 
  name: client-pod
  labels:
    component: web
spec:
  containers:
    - name: client
      image: ljinan/multi-client
      ports:
        - containerPort: 3000